## -----------------------------------------------
## Basic Configuration
## -----------------------------------------------

title = "Sentier des possibles"
copyright = "{year}"

## -----------------------------------------------
## Publish
## -----------------------------------------------

relativeURLs = "true"
#canonifyURLs = "true"

# Local
baseURL = "/"
publishDir = "public"

# Remote
#baseURL = "https://sentierdespossibles.fr"
#publishDir = "//centos/sites/hugodev/hugostory/"

## -----------------------------------------------
## Hugo Built-in Features
## -----------------------------------------------

disableKinds = ["taxonomy", "section"]
# googleAnalytics = "G-XXXXXXXXXX"

## -----------------------------------------------
## Site Parameters
## -----------------------------------------------

[Params]
  description = "Partager un bout de chemin ensemble et oser rêver à des horizons différents et des nouveaux possibles"
  logo = "images/Logo-SDP.jpg"
  favicon = true

[Params.social]
  email = "nils.lesieur@protonmail.com"
  linkedin = "https://www.linkedin.com/company/sentier-des-possibles"

[Params.asset]
  fontawesome_css = ["css/fontawesome-all.min.css"]
  fontawesome_js = ["js/fontawesome-all.min.js"]